spring.application.name=Avia2Spring
spring.datasource.url=jdbc:postgresql://localhost:6666/AviaSpring
spring.datasource.username=postgres
spring.datasource.password=coolCATZ2005rad!
admin.login=postgres
admin.password=coolCATZ2005rad!
server.port=8056
server.servlet.context-path=/Avia2Spring
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace